import './edit-standard';
import './create-standard';
import './fields';
import './standards-type-item.html';
import './standards-type-item.js';
import './standards-section-item.html';
import './standards-section-item.js';
import './standards-deleted-wrapper';
import './standards-wrapper';
