/* eslint-disable max-len */

export default {
  NOT_LOGGED_IN: 'You\'re not logged in',
  NOT_ORG_MEMBER: 'You\'re not a member of this organization',
  NOT_AUTHORIZED: 'You\'re not authorized for this action',
  NOT_FOUND: 'Document not found',
  USER_NOT_ORG_MEMBER: 'This user is not a member of your organization',
  USER_NOT_AUTHORIZED_FOR_EDITING: 'User is not authorized for editing this field',
  START_DATE_GTE_END_DATE: '"Start date" cannot be greater than or equal "end date"',
  END_DATE_LTE_START_DATE: '"End date" cannot be less than or equal "start date"',
  DOC_CANNOT_BE_COMPLETED: 'Document cannot be completed',
  DOC_CANNOT_BE_VERIFIED: 'Document cannot be verified',
  DOC_CANNOT_UNDO_COMPLETION: 'Cannot undo document completion',
  DOC_CANNOT_UNDO_VERIFICATION: 'Cannot undo document verification',
  DOC_SHOULD_BE_COMPLETED: 'Document should be completed',
  DOC_SHOULD_NOT_BE_COMPLETED: 'Document should not be completed',
  DOC_ALREADY_COMPLETED: 'Document is already completed',
  GOAL_CANNOT_CHANGE: 'Cannot create or change goal (Access denied)',
  LINKED_DOC_NOT_FOUND: 'Couldn\'t find linked document',
  COMPLETION_TARGET_DATE_BEFORE_START_DATE: '"Completion - target date" cannot be before start date',
  COMPLETION_TARGET_DATE_AFTER_END_DATE: '"Completion - target date" cannot be after end date',
  ORG_CANNOT_CHANGE_SETTINGS: 'User is not authorized for editing organization settings',
  DEP_CREATE_NOT_AUTHORIZED: 'User is not authorized for creating departments',
  PROJECT_CREATE_NOT_AUTHORIZED: 'User is not authorized for creating projects',
  ANALYSIS_CANT_COMPLETE: 'Can\'t complete analysis',
  ANALYSIS_CANT_UNDO_COMPLETION: 'Can\'t undo analysis completion',
  ANALYSIS_SHOULD_BE_COMPLETED: 'Analysis should be completed',
  ANALYSIS_SHOULD_BE_INCOMPLETE: 'Analysis should be incomplete',
  ANALYSIS_NOT_AUTHORIZED: 'User is not authorized for updating analysis',
  UNAUTHORIZED_CANT_UPLOAD: 'Unauthorized user cannot upload files',
  ACT_CANNOT_SET_COMPLETION_DATE_FOR_COMPLETED: 'Cannot set completion date for completed action',
  ACT_CANNOT_SET_EXECUTOR_FOR_COMPLETED: 'Cannot set executor for completed action',
  ST_CANNOT_CHANGE_DEFAULT: 'Cannot change or delete the default standard type',
};
