// Discussion types

export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_LOADING = 'SET_LOADING';

export const SET_SORT = 'SET_SORT';

export const SET_AT = 'SET_AT';

export const RESET = 'RESET';

export const SET_LAST_MESSAGE_ID = 'SET_LAST_MESSAGE_ID';

export const SET_PRIOR_LIMIT = 'SET_PRIOR_LIMIT';

export const SET_FOLLOWING_LIMIT = 'SET_FOLLOWING_LIMIT';

export const SET_RESET_COMPLETED = 'SET_RESET_COMPLETED';

export const SET_DISCUSSION = 'SET_DISCUSSION';

export const SET_IS_DISCUSSION_OPENED = 'SET_IS_DISCUSSION_OPENED';

// Standards types

export const INIT_SECTIONS = 'INIT_SECTIONS';

export const SET_SECTIONS = 'SET_SECTIONS';

export const SET_ALL_SECTIONS = 'SET_ALL_SECTIONS';

export const SET_STANDARDS = 'SET_STANDARDS';

export const INIT_TYPES = 'INIT_TYPES';

export const SET_TYPES = 'SET_TYPES';

export const SET_ALL_TYPES = 'SET_ALL_TYPES';

export const INIT_STANDARDS = 'INIT_STANDARDS';

export const SET_STANDARD = 'SET_STANDARD';

export const SET_IS_CARD_READY = 'SET_IS_CARD_READY';

export const SET_FILTERED_STANDARDS = 'SET_FILTERED_STANDARDS';

export const SET_FILTERED_SECTIONS = 'SET_FILTERED_SECTIONS';

export const SET_FILTERED_TYPES = 'SET_FILTERED_TYPES';

export const SET_IS_FULL_SCREEN_MODE = 'SET_IS_FULL_SCREEN_MODE';

// Organizations types

export const SET_ORG = 'SET_ORG';

export const SET_ORG_SERIAL_NUMBER = 'SET_ORG_SERIAL_NUMBER';

export const SET_ORG_ID = 'SET_ORG_ID';

// Changelog

export const SET_LOADING_LAST_HUMAN_LOG = 'SET_LOADING_LAST_HUMAN_LOG';

export const SET_LAST_HUMAN_LOG_LOADED = 'SET_LAST_HUMAN_LOG_LOADED';

export const SET_LOADING_LAST_LOGS = 'SET_LOADING_LAST_LOGS';

export const SET_LAST_LOGS_LOADED = 'SET_LAST_LOGS_LOADED';

export const SET_LOADING_ALL_LOGS = 'SET_LOADING_ALL_LOGS';

export const SET_ALL_LOGS_LOADED = 'SET_ALL_LOGS_LOADED';

export const SET_LOADING_LOGS_COUNT = 'SET_LOADING_LOGS_COUNT';

export const SET_LOGS_COUNT_LOADED = 'SET_LOGS_COUNT_LOADED';

export const SET_CHANGELOG_COLLAPSED = 'SET_CHANGELOG_COLLAPSED';

export const SET_LOGS = 'SET_LOGS';

export const SET_CHANGELOG_DOCUMENT_ID = 'SET_CHANGELOG_DOCUMENT_ID';

export const SET_CHANGELOG_DOCUMENT_COLLECTION = 'SET_CHANGELOG_DOCUMENT_COLLECTION';

export const SET_LAST_HUMAN_LOG = 'SET_LAST_HUMAN_LOG';

export const SET_CHANGELOG_DOCUMENT = 'SET_CHANGELOG_DOCUMENT';

export const SET_LOGS_COUNT = 'SET_LOGS_COUNT';

export const SET_SHOW_ALL = 'SET_SHOW_ALL';

// global

export const SET_FILTER = 'SET_FILTER';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const ADD_COLLAPSED = 'ADD_COLLAPSED';

export const REMOVE_COLLAPSED = 'REMOVE_COLLAPSED';

export const TOGGLE_COLLAPSED = 'TOGGLE_COLLAPSED';

export const SET_USER_ID = 'SET_USER_ID';

export const SET_ANIMATING = 'SET_ANIMATING';

export const SET_URL_ITEM_ID = 'SET_URL_ITEM_ID';

// collections

export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
