export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_LIMIT = 'SET_LIMIT';

export const SET_LOADING = 'SET_LOADING';

export const SET_SORT = 'SET_SORT';

export const SET_AT = 'SET_AT';

export const RESET = 'RESET';

export const SET_LAST_MESSAGE_ID = 'SET_LAST_MESSAGE_ID';

export const SET_SHOULD_SCROLL_TO_BOTTOM = 'SET_SHOULD_SCROLL_TO_BOTTOM';

export const SET_PRIOR_LIMIT = 'SET_PRIOR_LIMIT';

export const SET_FOLLOWING_LIMIT = 'SET_FOLLOWING_LIMIT';

export const SET_INITIAL_DATA_LOADED = 'SET_INITIAL_DATA_LOADED';
