// Discussion types

export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_DISCUSSION_LOADING = 'SET_DISCUSSION_LOADING';

export const SET_SORT = 'SET_SORT';

export const SET_AT = 'SET_AT';

export const RESET = 'RESET';

export const SET_LAST_MESSAGE_ID = 'SET_LAST_MESSAGE_ID';

export const SET_PRIOR_LIMIT = 'SET_PRIOR_LIMIT';

export const SET_FOLLOWING_LIMIT = 'SET_FOLLOWING_LIMIT';

export const SET_RESET_COMPLETED = 'SET_RESET_COMPLETED';

export const SET_DISCUSSION = 'SET_DISCUSSION';

export const SET_IS_DISCUSSION_OPENED = 'SET_IS_DISCUSSION_OPENED';

// Standards types

export const SET_FILTERED_STANDARDS = 'SET_FILTERED_STANDARDS';

export const SET_STANDARD_DEPS_READY = 'SET_STANDARD_DEPS_READY';

export const SET_STANDARDS_INITIALIZING = 'SET_STANDARDS_INITIALIZING';

// Risks types

export const SET_FILTERED_RISKS = 'SET_FILTERED_RISKS';

export const SET_RISK_DEPS_READY = 'SET_RISK_DEPS_READY';

export const SET_RISKS_INITIALIZING = 'SET_RISKS_INITIALIZING';

// Organization

export const SET_ORG = 'SET_ORG';

export const SET_ORG_SERIAL_NUMBER = 'SET_ORG_SERIAL_NUMBER';

export const SET_ORG_ID = 'SET_ORG_ID';

export const ORGANIZATION_CHANGED = 'ORGANIZATION_CHANGED';

// Changelog

export const SET_LOADING_LAST_HUMAN_LOG = 'SET_LOADING_LAST_HUMAN_LOG';

export const SET_LOADING_LAST_LOGS = 'SET_LOADING_LAST_LOGS';

export const SET_LAST_LOGS_LOADED = 'SET_LAST_LOGS_LOADED';

export const SET_LOADING_ALL_LOGS = 'SET_LOADING_ALL_LOGS';

export const SET_ALL_LOGS_LOADED = 'SET_ALL_LOGS_LOADED';

export const SET_LOADING_LOGS_COUNT = 'SET_LOADING_LOGS_COUNT';

export const SET_LOGS_COUNT = 'SET_LOGS_COUNT';

export const SET_LOGS = 'SET_LOGS';

export const SET_LAST_HUMAN_LOG = 'SET_LAST_HUMAN_LOG';

export const SET_CHANGELOG_DOCUMENT_DATA = 'SET_CHANGELOG_DOCUMENT_DATA';

export const SET_CHANGELOG_DOCUMENT = 'SET_CHANGELOG_DOCUMENT';

export const SET_CHANGELOG_COLLAPSED = 'SET_CHANGELOG_COLLAPSED';

export const SET_SHOW_ALL = 'SET_SHOW_ALL';

// global

export const SET_FILTER = 'SET_FILTER';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const ADD_COLLAPSED = 'ADD_COLLAPSED';

export const REMOVE_COLLAPSED = 'REMOVE_COLLAPSED';

export const TOGGLE_COLLAPSED = 'TOGGLE_COLLAPSED';

export const SET_USER_ID = 'SET_USER_ID';

export const SET_ANIMATING = 'SET_ANIMATING';

export const SET_URL_ITEM_ID = 'SET_URL_ITEM_ID';

export const SET_DATA_LOADING = 'SET_DATA_LOADING';

export const SET_IS_CARD_READY = 'SET_IS_CARD_READY';

export const SET_IS_FULL_SCREEN_MODE = 'SET_IS_FULL_SCREEN_MODE';

export const USER_LOGOUT = 'USER_LOGOUT';

// collections

export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';

export const SET_FILES = 'SET_FILES';

export const SET_STANDARDS = 'SET_STANDARDS';

export const SET_NCS = 'SET_NCS';

export const SET_RISKS = 'SET_RISKS';

export const SET_RISK_TYPES = 'SET_RISK_TYPES';

export const SET_ACTIONS = 'SET_ACTIONS';

export const SET_WORK_ITEMS = 'SET_WORK_ITEMS';

export const SET_STANDARD_BOOK_SECTIONS = 'SET_STANDARD_BOOK_SECTIONS';

export const SET_STANDARD_TYPES = 'SET_STANDARD_TYPES';

export const SET_LESSONS_LEARNED = 'SET_LESSONS_LEARNED';

export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';

export const ADD_STANDARD = 'ADD_STANDARD';

export const UPDATE_STANDARD = 'UPDATE_STANDARD';

export const REMOVE_STANDARD = 'REMOVE_STANDARD';

export const ADD_STANDARD_BOOK_SECTION = 'ADD_STANDARD_BOOK_SECTION';

export const UPDATE_STANDARD_BOOK_SECTION = 'UPDATE_STANDARD_BOOK_SECTION';

export const REMOVE_STANDARD_BOOK_SECTION = 'REMOVE_STANDARD_BOOK_SECTION';

export const ADD_STANDARD_TYPE = 'ADD_STANDARD_TYPE';

export const UPDATE_STANDARD_TYPE = 'UPDATE_STANDARD_TYPE';

export const REMOVE_STANDARD_TYPE = 'REMOVE_STANDARD_TYPE';

export const ADD_RISK = 'ADD_RISK';

export const UPDATE_RISK = 'UPDATE_RISK';

export const REMOVE_RISK = 'REMOVE_RISK';

export const ADD_RISK_TYPE = 'ADD_RISK_TYPE';

export const UPDATE_RISK_TYPE = 'UPDATE_RISK_TYPE';

export const REMOVE_RISK_TYPE = 'REMOVE_RISK_TYPE';

export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';

export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';

export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION';

export const SET_HELP_DOCS = 'SET_HELP_DOCS';

export const SET_HELP_SECTIONS = 'SET_HELP_SECTIONS';

export const SET_USERS = 'SET_USERS';

export const SET_USERS_BY_ORG_IDS = 'SET_USERS_BY_ORG_IDS';

export const SET_REVIEWS = 'SET_REVIEWS';

export const SET_PROJECTS = 'SET_PROJECTS';

// window

export const SET_WINDOW_WIDTH = 'SET_WINDOW_WIDTH';

// Mobile

export const SET_MOBILE_SHOW_CARD = 'SET_MOBILE_SHOW_CARD';

// Counters

export const SET_STANDARD_MESSAGES_NOT_VIEWED_COUNT_MAP =
  'SET_STANDARD_MESSAGES_NOT_VIEWED_COUNT_MAP';

// Customers

export const SET_CUSTOMERS_INITIALIZING = 'SET_CUSTOMERS_INITIALIZING';

export const SET_FILTERED_ORGANIZATIONS = 'SET_FILTERED_ORGANIZATIONS';

// Help Docs

export const SET_HELP_SECTIONS_DATA = 'SET_HELP_SECTIONS_DATA';

export const SET_FILTERED_HELP_DOCS = 'SET_FILTERED_HELP_DOCS';

// Modal

export const SET_MODAL = 'SET_MODAL';

export const SET_MODAL_SAVING = 'SET_MODAL_SAVING';

export const SET_MODAL_ERROR_TEXT = 'SET_MODAL_ERROR_TEXT';

export const ON_MODAL_CLOSE = 'ON_MODAL_CLOSE';

// DATA IMORT

export const SET_DATA_IMPORT_OWN_ORGS = 'SET_DATA_IMPORT_OWN_ORGS';

export const SET_DATA_IMPORT_ORGS_LOADING = 'SET_DATA_IMPORT_LOADING';

export const SET_DATA_IMPORT_ORGS_LOADED = 'SET_DATA_IMPORT_LOADED';

export const SET_DATA_IMPORT_ORGS_COLLAPSED = 'SET_DATA_IMPORT_ORGS_COLLAPSED';

export const SET_DATA_IMPORT_MODAL_OPENED_STATE = 'SET_DATA_IMPORT_MODAL_OPENED_STATE';

export const SET_DATA_IMPORT_IN_PROGRESS = 'SET_DATA_IMPORT_IN_PROGRESS';

export const SET_DATA_IMPORT_IDS = 'SET_DATA_IMPORT_IDS';
