import './departments';
import './nc-guidelines';
import './org-currency';
import './org-name';
import './org-transfer';
import './reminders';
import './standards-book-sections';
import './standards-types';
import './workflow-defaults';
